server:
  port: 8743
shiro:
  # 插件列表
  plugin-list:
    - com.mm.qbot.controller.BilibiliResolverController
#    - com.mikuac.example.plugins.PluginTwo
  # WebSocket 配置
  ws-config:
    # WebSocket 地址
    ws-url: "/ws/shiro"
    # 超时回收，默认10秒
    do-request-timeout: 100000
    # 二进制消息的最大长度
    max-binary-message-buffer-size: 512000
    # 最大空闲时间，超过这个时间将close session
    max-session-idle-timeout: 900000
    # 最大文本消息缓冲区
    max-text-message-buffer-size: 512000
  # 限速器（令牌桶算法）
  limiter:
    # 是否启用限速器
    enable: false
    # 每秒生成的令牌数
    permits-per-second: 1
  # 线程池配置
  task-pool:
    # 核心线程数（默认线程数）
    core-pool-size: 10
    # 缓冲队列大小
    queue-capacity: 200
    # 允许线程空闲时间（单位：默认为秒）
    keep-alive-time: 10
    # 最大线程数
    max-pool-size: 30
    # 线程池名前缀
    thread-name-prefix: "ShiroTaskPool-"
