server:
  port: 8743
shiro:
  # 插件列表
  plugin-list:
    - com.mm.qbot.controller.BilibiliCommandController
    - com.mm.qbot.controller.BilibiliGetNewDynamicController
#    - com.mikuac.example.plugins.PluginTwo
  # WebSocket 配置
  ws-config:
    # WebSocket 地址
    ws-url: "/ws/shiro"
    # 超时回收，默认10秒
    do-request-timeout: 100000
    # 二进制消息的最大长度
    max-binary-message-buffer-size: 512000
    # 最大空闲时间，超过这个时间将close session
    max-session-idle-timeout: 900000
    # 最大文本消息缓冲区
    max-text-message-buffer-size: 512000
  # 限速器（令牌桶算法）
  limiter:
    # 是否启用限速器
    enable: false
    # 每秒生成的令牌数
    permits-per-second: 1
  # 线程池配置
  task-pool:
    # 核心线程数（默认线程数）
    core-pool-size: 10
    # 缓冲队列大小
    queue-capacity: 200
    # 允许线程空闲时间（单位：默认为秒）
    keep-alive-time: 10
    # 最大线程数
    max-pool-size: 30
    # 线程池名前缀
    thread-name-prefix: "ShiroTaskPool-"
spring:
  redis:
    timeout: 3000
    host: localhost
    port: 6379
    password:
    database: 10
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 50
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000ms
        # 连接池中的最大空闲连接数
        max-idle: 20
        # 连接池中的最小空闲连接数
        min-idle: 5

logging:
  pattern:
    console: "%d{yyyy-MM-dd} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd} === [%thread] === %-5level === %logger{50} ==== %msg%n"
  file:
    path: G:\JavaProject\Qbot\log
  root:
    level: info
